version: '2.3'

services:
    dev:
        image: lecture_notes_on_compilers:dev
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: "host"
        environment:
            - CMAKE_EXPORT_COMPILE_COMMANDS=1
        volumes:
            - .:/mnt
        pid: host
        privileged: true
